from dotenv import load_dotenv
from weaviate import connect_to_weaviate_cloud, connect_to_embedded
from typing import Any, List, Optional, Dict
from pydantic import BaseModel, ConfigDict, Field
import uuid
import os
import requests
from weaviate.classes.init import Auth
from functools import cached_property, partial

from weaviate.collections.classes.config import Configure

load_dotenv()
HF_TOKEN = os.getenv("HUGGINGFACE_API_KEY")
HF_API_URL = "https://api-inference.huggingface.co/pipeline/feature-extraction/sentence-transformers/all-mpnet-base-v2"
HEADERS = {"Authorization": f"Bearer {HF_TOKEN}"}


class Document(BaseModel):
    id: str
    content: str
    metadata: Dict[str, Any] = {}
    vector: list[float] | None = None


class WeaviateVectorStorage:
    api_key: str | None = None
    url: str | None = None

    def __init__(self):
        """Initialize the Weaviate client and configure the collection"""
        self.api_key = self.api_key or os.getenv("WEAVIATE_API_KEY")
        self.url = self.url or os.getenv("WEAVIATE_URL")
        self.client = connect_to_weaviate_cloud(cluster_url=self.url, auth_credentials=Auth.api_key(self.api_key))
        print(self.client.is_ready())
        # Check if collection exists, create if not
        try:
            self.collection = self.client.collections.get("Documents125")
        except Exception as e:
            print(f"Collection retrieval failed: {e}")
            self.collection = self.client.collections.create(
                name="Documents125",
                properties=[
                    {"name": "content", "dataType": ["text"]},
                    {"name": "metadata", "dataType": ["object"]},
                ],
                vectorizer=Configure.Vectorizer.none(),
            )

    def _generate_uuid(self, doc_id: str) -> str:
        """Generate a deterministic UUID based on document ID"""
        return str(uuid.uuid4())

    def _generate_embedding(self, content: str) -> list[float]:
        response = requests.post(HF_API_URL, headers=HEADERS, json={"inputs": content})
        response.raise_for_status()
        embedding = response.json()
        return embedding

    def write_document(self, document: Document) -> str:
        """Write a single document WITHOUT manually passing embedding"""
        try:
            weaviate_id = self._generate_uuid(document.id)

            self.collection.data.insert(
                properties={
                    "content": document.content,
                    "metadata": document.metadata
                },
                uuid=weaviate_id,
                vector=self._generate_embedding(document.content),
                # NO vector field here → embedding auto-generated by Weaviate
            )
            return document.id
        except Exception as e:
            raise Exception(f"Error writing document: {str(e)}")

    def batch_write_documents(self, documents: List[Document]) -> int:
        """Batch insert without manual embedding"""
        with self.collection.batch.dynamic() as batch:
            written = 0
            for doc in documents:
                try:
                    weaviate_id = self._generate_uuid(doc.id)
                    batch.add_data_object(
                        data_object={
                            "content": doc.content,
                            "metadata": doc.metadata
                        },
                        class_name="Documents",
                        uuid=weaviate_id,
                        vector=self._generate_embedding(doc.content),
                        # again: no `vector` param
                    )
                    written += 1
                except Exception as e:
                    print(f"Error in batch write for document {doc.id}: {str(e)}")

        return written

    def delete_documents(self, document_ids: List[str] = None, delete_all: bool = False) -> int:
        """Delete documents by IDs or all documents"""
        deleted = 0

        if delete_all:
            self.collection.data.delete_many()
            return -1  # Indicate all documents deleted

        if document_ids:
            weaviate_ids = [self._generate_uuid(doc_id) for doc_id in document_ids]

            for weaviate_id in weaviate_ids:
                try:
                    self.collection.data.delete_by_id(weaviate_id)
                    deleted += 1
                except Exception as e:
                    print(f"Error deleting document {weaviate_id}: {str(e)}")

        return deleted

    def delete_documents_by_filters(self, filters: Dict[str, Any]) -> int:
        """Delete documents that match the given filters"""
        if not filters:
            raise ValueError("No filters provided")

        where_filter = self._convert_filters(filters)
        result = self.collection.data.delete_many(where=where_filter)
        return result.get("successful", 0)

    def _convert_filters(self, filters: Dict[str, Any]) -> Dict:
        """Convert API filters to Weaviate filters"""
        weaviate_filter = {}

        for key, value in filters.items():
            if key.startswith("metadata."):
                meta_key = key.replace("metadata.", "")
                path = ["metadata", meta_key]
                weaviate_filter["path"] = path

                if isinstance(value, (int, float, bool, str)):
                    weaviate_filter["operator"] = "Equal"
                    weaviate_filter["valueText"] = value
                elif isinstance(value, dict) and "operator" in value:
                    weaviate_filter["operator"] = value["operator"]
                    weaviate_filter["valueText"] = value["value"]
            else:
                weaviate_filter["path"] = [key]
                weaviate_filter["operator"] = "Equal"
                weaviate_filter["valueText"] = value

        return weaviate_filter

    def object_to_document(self, obj, include_vector: bool = False) -> Document:
        """Convert an object to a document instance"""
        metadata = {}
        if "metadata" in obj.properties and isinstance(obj.properties["metadata"], dict):
            # Case 1: Full metadata object is returned
            metadata.update(obj.properties["metadata"])
        else:
            # Case 2: Only metadata subfields are returned (e.g. via gRPC)
            for key, value in obj.properties.items():
                if key.startswith("metadata."):
                    # Strip "metadata." prefix and store as key
                    sub_key = key.split("metadata.")[1]
                    metadata[sub_key] = value

        return Document(
            content=obj.properties["content"],
            metadata=metadata,
            id=str(obj.uuid),
            vector=obj.vector["default"] if include_vector else None,
        )

    def update_document(self, document_id: str, content: str = None, metadata: Dict = None) -> bool:
        """Update an existing document"""
        weaviate_id = self._generate_uuid(document_id)

        try:
            existing = self.collection.query.get(["content", "metadata"]).with_id(weaviate_id).do()
            if not existing.objects:
                return False
        except Exception:
            return False

        properties = {}
        if content is not None:
            properties["content"] = content
        if metadata is not None:
            properties["metadata"] = metadata

        if not properties:
            return True

        try:
            self.collection.data.update(
                uuid=weaviate_id,
                properties=properties
            )
            return True
        except Exception:
            return False

    def list_documents(self, include_embeddings: bool = True) -> list[Document]:
        """
        List all documents in the DocumentStore.

        Args:
            include_embeddings (bool): Whether to include document embeddings in the result.
            content_key (Optional[str]): The field used to store content in the storage.

        Returns:
            list[Document]: A list of all documents in the store.
        """
        documents = []
        for item in self.collection.iterator(include_vector=include_embeddings):
            document = item
            documents.append(self.object_to_document(document, include_vector=include_embeddings))
        return documents

    def search_similar(self, query: str, filters: Dict[str, Any] = None, limit: int = 10,
                       include_embeddings: bool = False) -> List[Document]:
        """Search for documents similar to the query"""
        try:
            query_embedding = self._generate_embedding(query)
            result = self.collection.query.near_vector(
                near_vector=query_embedding,
                include_vector=include_embeddings,
                filters=self._convert_filters(filters) if filters else None,
                limit=limit,
                # return_properties=["content"]
            )

            documents = [self.object_to_document(document) for document in result.objects]

            return documents
        except Exception as e:
            raise Exception(f"Error searching documents: {str(e)}")

    def search_hybrid(self, query: str, filters: Dict[str, Any] = None, limit: int = 10, alpha: float = 0.5) -> List[
        Document]:
        """Perform hybrid search (combination of vector and keyword search)"""
        try:
            query_obj = self.collection.query.get(
                ["content", "metadata", "_additional {certainty}"]
            ).with_limit(limit)

            query_obj = query_obj.with_hybrid(
                query=query,
                alpha=alpha
            )

            if filters:
                where_filter = self._convert_filters(filters)
                query_obj = query_obj.with_where(where_filter)

            result = query_obj.do()

            documents = []
            for obj in result.objects:
                certainty = None
                if hasattr(obj, "additional"):
                    certainty = obj.additional.certainty

                doc = Document(
                    id=obj.id,
                    content=obj.properties["content"],
                    metadata=obj.properties["metadata"]
                )

                if certainty is not None:
                    doc.metadata["similarity_score"] = certainty

                documents.append(doc)

            return documents
        except Exception as e:
            raise Exception(f"Error performing hybrid search: {str(e)}")
